apiVersion: v1
kind: Service
metadata:
  name: demomongoqueen
  labels:
    app: demomongoqueen
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: demo