prometheus:
  rbac:
    create: false
  alertmanager:
    enabled: false
  configmapReload:
    prometheus:
      enabled: false
    alertmanager:
      enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false
  server:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    tolerations:
      - key: "metallica"
        operator: "Equal"
        value: "perf"
        effect: "NoSchedule"
  serverFiles:
      prometheus.yml:
        scrape_configs:
          - job_name: spring-boot-api-metrics
            metrics_path: '/actuator/prometheus'
            static_configs:
            - targets: 
              - demoqueenmongo:8080
          - job_name: mongodb-metrics
            static_configs:
            - targets:
              - my-mongodb-metrics:9216
tolerations:   
    - key: "metallica"
      operator: "Equal"
      value: "perf"
      effect: "NoSchedule"